services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks: [chocadies-net]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      MONGO_URI: mongodb://mongo:27017/chocadies
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      API_KEY: ${API_KEY:-partner-dev-key}
      BOOTSTRAP_SECRET: ${BOOTSTRAP_SECRET:-my-super-secret}
    depends_on:
      mongo:
        condition: service_healthy
    networks: [chocadies-net]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    networks: [chocadies-net]
    ports:
      - "8080:80"

networks:
  chocadies-net:

volumes:
  mongo_data:
